language: java

cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm

before_cache:
  - rm -rf $HOME/.m2/repository/org/keycloak

env:
  global:
    - MAVEN_SKIP_RC=true
    - MAVEN_OPTS="-Xms512m -Xmx1536m"
  matrix:
    - TESTS=unit
    - TESTS=server-group1
    - TESTS=server-group2
    - TESTS=server-group3
    - TESTS=server-group4
    - TESTS=adapter-tests
    - TESTS=adapter-tests-authz
    - TESTS=crossdc-server
    - TESTS=crossdc-adapter
    - TESTS=broker

matrix:
  include:
    - os: linux
      arch: s390x
      dist: bionic
      env: TESTS=unit
    - os: linux
      arch: s390x
      dist: bionic
      env: TESTS=server-group1
    - os: linux
      arch: s390x
      dist: bionic
      env: TESTS=server-group4
    - os: linux
      arch: s390x
      dist: bionic
      env: TESTS=crossdc-server
    - os: linux
      arch: s390x
      dist: bionic
      env: TESTS=crossdc-adapter
    - os: linux
      arch: s390x
      dist: bionic
      env: TESTS=broker

jdk:
  - openjdk8

install: true

before_install:
  - .travis/before_install.sh
  - if [[ $(uname -m) == 's390x' ]]; then 
      export QT_QPA_PLATFORM=offscreen;
      export PATH="$PWD/jdk8u252-b09/bin:$PATH";
    fi

before_script:
  - export -f travis_fold

script: 
  - ./travis-run-tests.sh $TESTS

after_success:
  - .travis/docker-hub-master-trigger.sh

sudo: false
