language: java

arch: 
  - amd64   
  - s390x
  
cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm

before_cache:
  - rm -rf $HOME/.m2/repository/org/keycloak

env:
  global:
    - PHANTOMJS_VERSION=2.1.1
    - MAVEN_SKIP_RC=true
    - MAVEN_OPTS="-Xms512m -Xmx1536m"
  matrix:
    - TESTS=unit
    - TESTS=server-group1
    - TESTS=server-group2
    - TESTS=server-group3
    - TESTS=server-group4
    - TESTS=adapter-tests
    - TESTS=adapter-tests-authz
    - TESTS=crossdc-server
    - TESTS=crossdc-adapter
    - TESTS=broker

jdk:
  - openjdk8

install: true

before_install:
  - "if [ $TRAVIS_ARCH = s390x ]; then sudo apt-get install phantomjs; export QT_QPA_PLATFORM=offscreen; export PATH=$PATH fi"
  - "if [ $TRAVIS_ARCH = amd64 ]; then export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH; fi"
  - "phantomjs --version"
  - "if [ $TRAVIS_ARCH = amd64 -a $(phantomjs --version) != '$PHANTOMJS_VERSION' ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $TRAVIS_ARCH = amd64 -a $(phantomjs --version) != '$PHANTOMJS_VERSION' ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi"
  - "if [ $TRAVIS_ARCH = amd64 -a $(phantomjs --version) != '$PHANTOMJS_VERSION' ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "phantomjs --version"

before_script:
  - export -f travis_fold

script: 
  - ./travis-run-tests.sh $TESTS

after_success:
  - .travis/docker-hub-master-trigger.sh

sudo: false
