language: java

arch: 
   - s390x

dist:
   - bionic

cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm

before_cache:
  - rm -rf $HOME/.m2/repository/org/keycloak

env:
  global:
    - MAVEN_SKIP_RC=true
    - MAVEN_OPTS="-Xms512m -Xmx1536m"
  matrix:
    - TESTS=unit
    - TESTS=server-group1
    - TESTS=server-group2
    - TESTS=server-group3
    - TESTS=server-group4
    - TESTS=adapter-tests
    - TESTS=adapter-tests-authz
    - TESTS=crossdc-server
    - TESTS=crossdc-adapter
    - TESTS=broker

install: true

before_install:
  - sudo apt-get install maven
  - curl -fsSL https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u252-b09_openj9-0.20.0/OpenJDK8U-jdk_s390x_linux_openj9_8u252b09_openj9-0.20.0.tar.gz | tar xz 
  - export PATH="$PWD/jdk8u252-b09/bin:$PATH"
  - mvn --version
  - sudo env "PATH=$PATH" .travis/before_install.sh

before_script:
  - export -f travis_fold

script:
  - mvn --version 
  - ./travis-run-tests.sh $TESTS

after_success:
  - .travis/docker-hub-master-trigger.sh

sudo: false
